[settings]
lockfile = true
python.uv_venv_auto = "source"
lockfile_platforms = ["macos-arm64", "linux-x64", "linux-arm64"]

[tools]
cargo-binstall = "latest"
usage = "latest"
"cargo:guartcl" = "0.5.0"
uv = "latest"
jq = "latest"

[tool_alias]
guartcl = "forgejo:mdekstrand/rust-jim"

[env]
JIMLIB = "{{config_root}}/lib"
