name: Publish Documentation Site
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-site:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out doc site
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.63.0
          policy_allow: true

      - name: "🌳 Fix local git branches"
        run: just ref-branches

      - name: Build site content
        run: just build

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: lenskit-site
          path: site

  publish-github:
    name: Upload to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build-site]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Fetch site artifact
        uses: actions/download-artifact@v4
        with:
          name: lenskit-site
          path: .
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
